logging:
  file: "/home/andreyakor/Документы/OTUS/Разработчик Golang/Домашки/image_previewer.log"
  level: "debug"

http:
  host: "0.0.0.0"
  port: 6080
  bodyLimit: 1048576

client:
  timeout: "30s"
  bodyLimit: 3145728

image:
  maxWidth: 4096
  maxHeight: 3072

cache:
  capacity: 3
